package podify;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

// -------------------------------------------------------------------------
/**
 *  Reads the song list that was generated by an LLM and stores the valid
 *  songs. The file is a CSV file with this header and column order:
 *
 *      id,title,artist,duration,genre,playCount
 *
 *  Rows that are damaged (missing columns, empty fields, a play count that
 *  is not a number, a bad duration, or a repeated id) are skipped instead
 *  of crashing the program.
 *
 *  This class only holds the imported songs. It never changes the user's
 *  own playlist. The user picks songs from here and UserPlaylist stores
 *  them.
 *
 *  @author Dochan (Logan) Moon
 *  @version 20 Sept 2026
 */
public class PlaylistLLM {

    //~ Fields ................................................................

    /** The longest title or artist name we accept. */
    public static final int MAX_TEXT_LENGTH = 30;

    /** Number of columns every row of the CSV file must have. */
    private static final int COLUMN_COUNT = 6;

    // An ArrayList is used because the songs must stay in the same order as
    // the file, and because we need to look at them by index when we show
    // the list to the user.
    private List<Song> importedSongs;

    // The last problem that happened. The user interface can print this so
    // the user knows what went wrong and how to fix it.
    private String lastError;

    // How many rows of the file were damaged and had to be skipped.
    private int skippedRows;


    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new PlaylistLLM with no songs imported yet.
     */
    public PlaylistLLM() {
        importedSongs = new ArrayList<Song>();
        lastError = "";
        skippedRows = 0;
    }


    //~ Public Methods ........................................................

    // ----------------------------------------------------------
    /**
     * Reads the LLM file and creates a Song object for every valid row.
     *
     * @param fileName the path of the CSV file, for example
     *                 "data/llm_playlist.csv"
     * @return true if at least one song was loaded, false if the file could
     *         not be opened or had no usable rows
     */
    public boolean loadSongs(String fileName) {
        lastError = "";
        skippedRows = 0;

        if (fileName == null || fileName.trim().isEmpty()) {
            lastError = "No file name was given.";
            return false;
        }

        // The songs go into a temporary list first. If anything goes wrong
        // we return false and importedSongs is left exactly as it was, so a
        // bad file can never damage songs that were already loaded.
        List<Song> loaded = new ArrayList<Song>();

        // Ids we have already seen in this file, used to reject duplicates.
        List<String> usedIds = new ArrayList<String>();

        // try-with-resources: the Scanner is closed automatically when this
        // block ends, even if an error happens inside it.
        try (Scanner reader = new Scanner(new File(fileName))) {
            boolean firstLine = true;

            while (reader.hasNextLine()) {
                String line = reader.nextLine();

                // The first line is the header, so skip it. We compare in
                // lower case so "playCount" and "playcount" both work.
                if (firstLine) {
                    firstLine = false;
                    if (line.toLowerCase().startsWith("id,")) {
                        continue;
                    }
                }

                // Completely blank lines are ignored and not counted as
                // errors, because text files often end with one.
                if (line.trim().isEmpty()) {
                    continue;
                }

                Song song = readRow(line, usedIds);
                if (song == null) {
                    skippedRows++;
                }
                else {
                    loaded.add(song);
                }
            }
        }
        catch (FileNotFoundException e) {
            lastError = "Could not open the file \"" + fileName
                + "\". Check that the name is spelled correctly and that "
                + "the file is in the right folder, then try again.";
            return false;
        }

        if (loaded.isEmpty()) {
            lastError = "The file \"" + fileName
                + "\" did not contain any usable songs.";
            return false;
        }

        // Only now do we replace the real list.
        importedSongs = loaded;

        if (skippedRows > 0) {
            lastError = "Loaded " + loaded.size() + " songs, but skipped "
                + skippedRows + " damaged row(s) in the file.";
        }
        return true;
    }


    // ----------------------------------------------------------
    /**
     * Finds every imported song whose title or artist contains the query.
     * The search ignores upper and lower case, so "weeknd" finds
     * "The Weeknd".
     *
     * @param query the text to look for
     * @return the matching songs, or an empty list if nothing matches or
     *         the query is not allowed
     */
    public List<Song> searchSongs(String query) {
        lastError = "";
        List<Song> results = new ArrayList<Song>();

        if (query == null || query.trim().isEmpty()) {
            lastError = "Search cannot be blank. Type a title or an artist.";
            return results;
        }

        if (query.length() > MAX_TEXT_LENGTH) {
            lastError = "Search text is too long. The limit is "
                + MAX_TEXT_LENGTH + " characters.";
            return results;
        }

        String wanted = query.trim().toLowerCase();

        for (int i = 0; i < importedSongs.size(); i++) {
            Song song = importedSongs.get(i);
            String title = song.getName().toLowerCase();
            String artist = song.getArtist().toLowerCase();

            if (title.contains(wanted) || artist.contains(wanted)) {
                results.add(song);
            }
        }

        if (results.isEmpty()) {
            lastError = "Song not found. No title or artist contains \""
                + query.trim() + "\".";
        }
        return results;
    }


    // ----------------------------------------------------------
    /**
     * Finds the imported song with this exact title. Upper and lower case
     * are ignored so the user does not have to match it perfectly.
     *
     * @param title the full title of the song
     * @return the matching Song, or null if no imported song has that title
     */
    public Song getSong(String title) {
        lastError = "";

        if (title == null || title.trim().isEmpty()) {
            lastError = "Song title cannot be blank.";
            return null;
        }

        String wanted = title.trim();

        for (int i = 0; i < importedSongs.size(); i++) {
            Song song = importedSongs.get(i);
            if (song.getName().equalsIgnoreCase(wanted)) {
                return song;
            }
        }

        lastError = "Song not found: \"" + wanted + "\".";
        return null;
    }


    // ----------------------------------------------------------
    /**
     * Gets the songs that were imported from the file.
     *
     * @return a copy of the imported song list
     */
    public List<Song> getImportedSongs() {
        // A copy is returned so that other classes cannot add or remove
        // songs from our list by accident. They still share the same Song
        // objects, which is what we want, because playing a song must
        // update the same object everywhere.
        return new ArrayList<Song>(importedSongs);
    }


    // ----------------------------------------------------------
    /**
     * Gets how many songs are currently imported.
     *
     * @return the number of imported songs
     */
    public int numberImportedSongs() {
        return importedSongs.size();
    }


    // ----------------------------------------------------------
    /**
     * Gets the message that explains the last problem. It is an empty
     * string when the last action worked.
     *
     * @return the error message for the user
     */
    public String getLastError() {
        return lastError;
    }


    // ----------------------------------------------------------
    /**
     * Gets how many damaged rows were skipped by the last loadSongs call.
     *
     * @return the number of skipped rows
     */
    public int getSkippedRows() {
        return skippedRows;
    }


    //~ Private Methods .......................................................

    // ----------------------------------------------------------
    /**
     * Turns one line of the CSV file into a Song, or returns null when the
     * row is damaged. Returning null instead of throwing an exception lets
     * loadSongs skip the bad row and keep reading the rest of the file.
     *
     * @param line    one line from the file
     * @param usedIds the ids already seen in this file, added to when the
     *                row is accepted
     * @return the new Song, or null if the row cannot be used
     */
    private Song readRow(String line, List<String> usedIds) {
        // The -1 matters. Without it, split throws away empty fields at the
        // end, so a row like "S002,Starboy,The Weeknd,3:50,R&B," would look
        // like it has 5 columns instead of 6 and the error would be wrong.
        String[] parts = line.split(",", -1);

        if (parts.length != COLUMN_COUNT) {
            return null;
        }

        String id = parts[0].trim();
        String title = parts[1].trim();
        String artist = parts[2].trim();
        String duration = parts[3].trim();
        String genre = parts[4].trim();
        String countText = parts[5].trim();

        // Every column must actually contain something.
        if (id.isEmpty() || title.isEmpty() || artist.isEmpty()
            || duration.isEmpty() || genre.isEmpty() || countText.isEmpty()) {
            return null;
        }

        if (title.length() > MAX_TEXT_LENGTH
            || artist.length() > MAX_TEXT_LENGTH) {
            return null;
        }

        if (!isValidDuration(duration)) {
            return null;
        }

        // The LLM gives every song its own id, so the same id twice means
        // the file lists the same song twice. We keep the first one.
        if (usedIds.contains(id)) {
            return null;
        }

        int playCount;
        try {
            playCount = Integer.parseInt(countText);
        }
        catch (NumberFormatException e) {
            // The play count was something like "abc".
            return null;
        }

        if (playCount < 0) {
            return null;
        }

        usedIds.add(id);

        // Note the order: Song's constructor takes playCount BEFORE genre,
        // which is not the order the columns are in.
        return new Song(title, artist, duration, playCount, genre);
    }


    // ----------------------------------------------------------
    /**
     * Checks that a duration looks like M:SS or MM:SS, for example "3:51".
     *
     * @param text the duration from the file
     * @return true if the format is correct
     */
    private boolean isValidDuration(String text) {
        int colon = text.indexOf(':');

        // There must be a colon, at least one digit before it, and exactly
        // two characters after it.
        if (colon < 1 || colon != text.length() - 3) {
            return false;
        }

        for (int i = 0; i < text.length(); i++) {
            if (i != colon && !Character.isDigit(text.charAt(i))) {
                return false;
            }
        }
        return true;
    }
}
