package podify;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

// -------------------------------------------------------------------------
/**
 *  Reads the song list that was generated by an LLM and stores the valid
 *  songs. The file is a CSV file with this header and column order:
 *
 *   id,title,artist,duration,genre,playCount
 *
 *  Rows that are damaged (missing columns, empty fields, a play count that
 *  is not a number, or a bad duration) are skipped instead of crashing the
 *  program. Rows that repeat an id that was already seen are skipped too,
 *  but they are counted separately so the user interface can show a real
 *  duplicate warning instead of calling the row damaged.
 *
 *  This class also writes the file back out again. That is how the scope
 *  document's "save the playlist and play counts locally" requirement is
 *  met: the same CSV format is used for reading and for writing, so a saved
 *  file can be loaded again the next time the program starts.
 *
 *  This class only holds the imported songs. It never changes the user's
 *  own playlist. The user picks songs from here and UserPlaylist stores
 *  them.
 *
 *  @author Dochan (Logan) Moon
 *  @version 20 Sept 2026
 */
public class PlaylistLLM {

    //~ Fields ................................................................

    /** The longest title or artist name we accept. */
    public static final int MAX_TEXT_LENGTH = 30;

    /** The header line that every saved file starts with. */
    public static final String HEADER = "id,title,artist,duration,genre,"
        + "playCount";

    /** Number of columns every row of the CSV file must have. */
    private static final int COLUMN_COUNT = 6;

    /** The largest number of seconds a duration may show. */
    private static final int SECONDS_PER_MINUTE = 60;

    // An ArrayList is used because the songs must stay in the same order as
    // the file, and because we need to look at them by index when we show
    // the list to the user.
    private List<Song> importedSongs;

    // The last problem that happened. The user interface can print this so
    // the user knows what went wrong and how to fix it.
    private String lastError;

    // How many rows of the file were broken in some way and had to be
    // thrown away.
    private int damagedRows;

    // How many rows repeated an id we had already read. These are counted
    // on their own because the scope document asks for a duplicate warning,
    // which is a different message than "the file is damaged".
    private int duplicateRows;


    //~ Constructors ..........................................................

    // ----------------------------------------------------------
    /**
     * Creates a new PlaylistLLM with no songs imported yet.
     */
    public PlaylistLLM() {
        importedSongs = new ArrayList<Song>();
        lastError = "";
        damagedRows = 0;
        duplicateRows = 0;
    }


    //~ Public Methods ........................................................

    // ----------------------------------------------------------
    /**
     * Reads the LLM file and creates a Song object for every valid row.
     *
     * @param fileName the path of the CSV file, for example
     *                 "data/llm_playlist.csv"
     * @return true if at least one song was loaded, false if the file could
     *         not be opened or had no usable rows
     */
    public boolean loadSongs(String fileName) {
        lastError = "";
        damagedRows = 0;
        duplicateRows = 0;

        if (fileName == null || fileName.trim().isEmpty()) {
            lastError = "No file name was given.";
            return false;
        }

        // The songs go into a temporary list first. If anything goes wrong
        // we return false and importedSongs is left exactly as it was, so a
        // bad file can never damage songs that were already loaded.
        List<Song> loaded = new ArrayList<Song>();

        // Ids we have already seen in this file, used to reject duplicates.
        List<String> usedIds = new ArrayList<String>();

        // try-with-resources: the Scanner is closed automatically when this
        // block ends, even if an error happens inside it.
        try (Scanner reader = new Scanner(new File(fileName))) {
            boolean firstLine = true;

            while (reader.hasNextLine()) {
                String line = reader.nextLine();

                // The first line is the header, so skip it. We compare in
                // lower case so "playCount" and "playcount" both work.
                if (firstLine) {
                    firstLine = false;
                    if (line.toLowerCase().startsWith("id,")) {
                        continue;
                    }
                }

                // Completely blank lines are ignored and not counted as
                // errors, because text files often end with one.
                if (line.trim().isEmpty()) {
                    continue;
                }

                readRow(line, usedIds, loaded);
            }
        }
        catch (FileNotFoundException e) {
            lastError = "Could not open the file \"" + fileName
                + "\". Check that the name is spelled correctly and that "
                + "the file is in the right folder, then try again.";
            return false;
        }

        if (loaded.isEmpty()) {
            lastError = "The file \"" + fileName
                + "\" did not contain any usable songs.";
            return false;
        }

        // Only now do we replace the real list.
        importedSongs = loaded;

        buildSkippedMessage(loaded.size());
        return true;
    }


    // ----------------------------------------------------------
    /**
     * Writes songs out in the same CSV format that loadSongs reads, so the
     * playlist and its play counts are still there the next time the
     * program starts.
     *
     * Nothing is written when a song holds a comma, because a comma would
     * split one column into two and the file could no longer be read back.
     * Refusing to write is safer than saving a file that is already broken.
     *
     * @param fileName the path to write to, for example "data/saved.csv"
     * @param songs    the songs to write
     * @return true when the file was written, false when it was not
     */
    public boolean saveSongs(String fileName, List<Song> songs) {
        lastError = "";

        if (fileName == null || fileName.trim().isEmpty()) {
            lastError = "No file name was given.";
            return false;
        }

        if (songs == null) {
            lastError = "There was no song list to save.";
            return false;
        }

        // The whole list is checked before a single line is written. If a
        // song is bad we stop here, and the file on disk is left untouched.
        for (int i = 0; i < songs.size(); i++) {
            Song song = songs.get(i);
            if (song == null) {
                lastError = "The song list contains an empty slot, so "
                    + "nothing was saved.";
                return false;
            }
            if (hasComma(song)) {
                lastError = "\"" + song.getName() + "\" contains a comma, "
                    + "which cannot be saved in a CSV file. Rename the song "
                    + "and try again.";
                return false;
            }
        }

        try (PrintWriter writer = new PrintWriter(new File(fileName))) {
            writer.println(HEADER);

            for (int i = 0; i < songs.size(); i++) {
                writer.println(buildRow(songs.get(i), i));
            }
        }
        catch (FileNotFoundException e) {
            lastError = "Could not write to the file \"" + fileName
                + "\". Check that the folder exists and that the file is "
                + "not read-only, then try again.";
            return false;
        }

        return true;
    }


    // ----------------------------------------------------------
    /**
     * Saves the user's own playlist, which is the list whose play counts
     * actually change while the program runs.
     *
     * @param fileName the path to write to
     * @param playlist the user's playlist
     * @return true when the file was written, false when it was not
     */
    public boolean savePlaylist(String fileName, UserPlaylist playlist) {
        lastError = "";

        if (playlist == null) {
            lastError = "There was no playlist to save.";
            return false;
        }

        return saveSongs(fileName, playlist.getSongs());
    }


    // ----------------------------------------------------------
    /**
     * Finds every imported song whose title or artist contains the query.
     * The search ignores upper and lower case, so "weeknd" finds
     * "The Weeknd".
     *
     * @param query the text to look for
     * @return the matching songs, or an empty list if nothing matches or
     *         the query is not allowed
     */
    public List<Song> searchSongs(String query) {
        lastError = "";
        List<Song> results = new ArrayList<Song>();

        if (query == null || query.trim().isEmpty()) {
            lastError = "Search cannot be blank. Type a title or an artist.";
            return results;
        }

        if (query.length() > MAX_TEXT_LENGTH) {
            lastError = "Search text is too long. The limit is "
                + MAX_TEXT_LENGTH + " characters.";
            return results;
        }

        String wanted = query.trim().toLowerCase();

        for (int i = 0; i < importedSongs.size(); i++) {
            Song song = importedSongs.get(i);
            String title = song.getName().toLowerCase();
            String artist = song.getArtist().toLowerCase();

            if (title.contains(wanted) || artist.contains(wanted)) {
                results.add(song);
            }
        }

        if (results.isEmpty()) {
            lastError = "Song not found. No title or artist contains \""
                + query.trim() + "\".";
        }
        return results;
    }


    // ----------------------------------------------------------
    /**
     * Finds the imported song with this exact title. Upper and lower case
     * are ignored so the user does not have to match it perfectly.
     *
     * @param title the full title of the song
     * @return the matching Song, or null if no imported song has that title
     */
    public Song getSong(String title) {
        lastError = "";

        if (title == null || title.trim().isEmpty()) {
            lastError = "Song title cannot be blank.";
            return null;
        }

        String wanted = title.trim();

        for (int i = 0; i < importedSongs.size(); i++) {
            Song song = importedSongs.get(i);
            if (song.getName().equalsIgnoreCase(wanted)) {
                return song;
            }
        }

        lastError = "Song not found: \"" + wanted + "\".";
        return null;
    }


    // ----------------------------------------------------------
    /**
     * Finds the imported song that the LLM gave this id. Ids are the only
     * thing that is guaranteed to be unique, so this is what the menu uses
     * when the user picks a song out of the imported list.
     *
     * @param songId the id from the file, for example "S001"
     * @return the matching Song, or null if no imported song has that id
     */
    public Song getSongById(String songId) {
        lastError = "";

        if (songId == null || songId.trim().isEmpty()) {
            lastError = "Song id cannot be blank.";
            return null;
        }

        String wanted = songId.trim();

        for (int i = 0; i < importedSongs.size(); i++) {
            Song song = importedSongs.get(i);
            if (wanted.equalsIgnoreCase(song.getId())) {
                return song;
            }
        }

        lastError = "Song not found for id \"" + wanted + "\".";
        return null;
    }


    // ----------------------------------------------------------
    /**
     * Gets the songs that were imported from the file.
     *
     * @return a copy of the imported song list
     */
    public List<Song> getImportedSongs() {
        // A copy is returned so that other classes cannot add or remove
        // songs from our list by accident. They still share the same Song
        // objects, which is what we want, because playing a song must
        // update the same object everywhere.
        return new ArrayList<Song>(importedSongs);
    }


    // ----------------------------------------------------------
    /**
     * Gets how many songs are currently imported.
     *
     * @return the number of imported songs
     */
    public int numberImportedSongs() {
        return importedSongs.size();
    }


    // ----------------------------------------------------------
    /**
     * Gets the message that explains the last problem. It is an empty
     * string when the last action worked.
     *
     * @return the error message for the user
     */
    public String getLastError() {
        return lastError;
    }


    // ----------------------------------------------------------
    /**
     * Gets how many rows the last loadSongs call threw away, counting both
     * damaged rows and duplicates.
     *
     * @return the number of skipped rows
     */
    public int getSkippedRows() {
        return damagedRows + duplicateRows;
    }


    // ----------------------------------------------------------
    /**
     * Gets how many rows were thrown away because something in them was
     * broken, not counting duplicates.
     *
     * @return the number of damaged rows
     */
    public int getDamagedRows() {
        return damagedRows;
    }


    // ----------------------------------------------------------
    /**
     * Gets how many rows repeated an id that had already been read. The
     * scope document asks for a duplicate warning, so this is kept apart
     * from the damaged row count.
     *
     * @return the number of duplicate rows
     */
    public int getDuplicateRows() {
        return duplicateRows;
    }


    //~ Private Methods .......................................................

    // ----------------------------------------------------------
    /**
     * Turns one line of the CSV file into a Song and adds it to the list.
     * A bad row is counted instead of being added, which lets loadSongs
     * keep reading the rest of the file rather than stopping on the first
     * mistake.
     *
     * @param line    one line from the file
     * @param usedIds the ids already seen in this file, added to when the
     *                row is accepted
     * @param loaded  the list the new Song is added to
     */
    private void readRow(String line, List<String> usedIds,
        List<Song> loaded) {

        // The -1 matters. Without it, split throws away empty fields at the
        // end, so a row like "S002,Starboy,The Weeknd,3:50,R&B," would look
        // like it has 5 columns instead of 6 and the error would be wrong.
        String[] parts = line.split(",", -1);

        if (parts.length != COLUMN_COUNT) {
            damagedRows++;
            return;
        }

        String id = parts[0].trim();
        String title = parts[1].trim();
        String artist = parts[2].trim();
        String duration = parts[3].trim();
        String genre = parts[4].trim();
        String countText = parts[5].trim();

        // Every column must actually contain something.
        if (id.isEmpty() || title.isEmpty() || artist.isEmpty()
            || duration.isEmpty() || genre.isEmpty() || countText.isEmpty()) {
            damagedRows++;
            return;
        }

        if (title.length() > MAX_TEXT_LENGTH
            || artist.length() > MAX_TEXT_LENGTH) {
            damagedRows++;
            return;
        }

        if (!isValidDuration(duration)) {
            damagedRows++;
            return;
        }

        int playCount;
        try {
            playCount = Integer.parseInt(countText);
        }
        catch (NumberFormatException e) {
            // The play count was something like "abc".
            damagedRows++;
            return;
        }

        if (playCount < 0) {
            damagedRows++;
            return;
        }

        // The LLM gives every song its own id, so the same id twice means
        // the file lists the same song twice. We keep the first one. This
        // check comes last so that a row that is both broken and a
        // duplicate is reported as broken, which is the more useful
        // message.
        if (containsIgnoreCase(usedIds, id)) {
            duplicateRows++;
            return;
        }

        usedIds.add(id);

        // Note the order: Song's constructor takes playCount BEFORE genre,
        // which is not the order the columns are in.
        loaded.add(new Song(id, title, artist, duration, playCount, genre));
    }


    // ----------------------------------------------------------
    /**
     * Builds the message the user sees after a load that skipped rows. It
     * is left empty when the whole file was clean.
     *
     * @param loadedCount how many songs were actually loaded
     */
    private void buildSkippedMessage(int loadedCount) {
        if (getSkippedRows() == 0) {
            return;
        }

        String message = "Loaded " + loadedCount + " songs";

        if (damagedRows > 0) {
            message = message + ", skipped " + damagedRows
                + " damaged row(s)";
        }

        if (duplicateRows > 0) {
            message = message + ", ignored " + duplicateRows
                + " duplicate song(s) already listed in the file";
        }

        lastError = message + ".";
    }


    // ----------------------------------------------------------
    /**
     * Turns one Song back into a CSV line. A song that was built by hand
     * has no id, so one is made up from its position in the list. Without
     * an id the saved file could not be read back, because loadSongs treats
     * an empty id column as a damaged row.
     *
     * @param song     the song to write
     * @param position where the song sits in the list, counting from zero
     * @return the line to write to the file
     */
    private String buildRow(Song song, int position) {
        String id = song.getId();

        if (id == null || id.trim().isEmpty()) {
            id = "S" + (position + 1);
        }

        return id + "," + song.getName() + "," + song.getArtist() + ","
            + song.getDuration() + "," + song.getGenre() + ","
            + song.getPlayCount();
    }


    // ----------------------------------------------------------
    /**
     * Checks whether any of the song's text fields holds a comma, which is
     * the one character that a plain CSV file cannot store.
     *
     * @param song the song to check
     * @return true if the song cannot be written safely
     */
    private boolean hasComma(Song song) {
        return contains(song.getId()) || contains(song.getName())
            || contains(song.getArtist()) || contains(song.getDuration())
            || contains(song.getGenre());
    }


    // ----------------------------------------------------------
    /**
     * Checks one field for a comma. A null field counts as safe, because
     * buildRow replaces a missing id with one it makes up.
     *
     * @param field the text to check
     * @return true if the text holds a comma
     */
    private boolean contains(String field) {
        return field != null && field.indexOf(',') >= 0;
    }


    // ----------------------------------------------------------
    /**
     * Looks for an id in the list of ids already seen, ignoring case, so
     * that "s001" and "S001" count as the same song.
     *
     * @param ids    the ids seen so far
     * @param wanted the id to look for
     * @return true if the id was already used
     */
    private boolean containsIgnoreCase(List<String> ids, String wanted) {
        for (int i = 0; i < ids.size(); i++) {
            if (ids.get(i).equalsIgnoreCase(wanted)) {
                return true;
            }
        }
        return false;
    }


    // ----------------------------------------------------------
    /**
     * Checks that a duration looks like M:SS or MM:SS, for example "3:51",
     * and that the seconds are a real number of seconds. "3:75" has the
     * right shape but no song is 75 seconds into a minute, so it is
     * rejected.
     *
     * @param text the duration from the file
     * @return true if the format is correct
     */
    private boolean isValidDuration(String text) {
        // Find where the colon that separates minutes from seconds sits.
        // indexOf returns the index of the first ':' in the string, or -1
        // if the string has no colon at all.
        int colon = text.indexOf(':');

        // There must be a colon, at least one digit before it, and exactly
        // two characters after it.
        // "3:51"   length = 4,  colon index = 1,  4 - 3 = 1
        if (colon < 1 || colon != text.length() - 3) {
            return false;
        }

        // Every character except the colon must be a digit.
        for (int i = 0; i < text.length(); i++) {
            if (i != colon && !Character.isDigit(text.charAt(i))) {
                return false;
            }
        }

        // The two characters after the colon are digits, so parsing them
        // cannot fail here.
        int seconds = Integer.parseInt(text.substring(colon + 1));
        return seconds < SECONDS_PER_MINUTE;
    }
}
